# add server info
- name: Tanuki-8B-Instruct
  PORT: 8000
  model: hatakeyama-llm-team/Tanuki-8B-Instruct
  max-model-len: 4000
  gpu-memory-utilization: 0.2
  GPU_ID: 1
  template1: ""
  template2: ""

- name: Phi-3-medium-128k-instruct
  PORT: 8001
  model: microsoft/Phi-3-medium-128k-instruct
  max-model-len: 4000
  gpu-memory-utilization: 0.4
  GPU_ID: 1

#templateがうまくいかない
#- name: RakutenAI-7B-chat
#  PORT: 8002
#  model: Rakuten/RakutenAI-7B-chat
#  max-model-len: 4000
#  gpu-memory-utilization: 0.2
#  GPU_ID: 0
#  #template: templates/RakutenAI-7B-chat.jinja

